[package]
name = "photosquid"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.2"
nalgebra-glm = "0.15.0"
raster = "0.2.0"
tobj = "3.2.0"
stringreader = "0.1.1"
interpolation = "0.2.0"
slotmap = "1.0.6"
palette = "0.6.0"
glium_text_rusttype = { path = "../glium_text_rusttype" }
rand = "0.7"
enum-as-inner = "0.3.3"
angular-units = "0.2.4"
lyon="0.17.10"
more-asserts="0.2.2"
strum_macros = "0.13.0"

# serde = { version = "1.0", features = ["derive"] }
# bincode = "1.2.1"
# approx = "0.5.0"
